name: CI/CD
on: [push, workflow_dispatch]

jobs:
  test_and_deploy:
    name: Test and Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Install dependencies
        uses: actions/setup-node@v7
        with:
          node-version: '26'
      - name: Set up environment
        run: |
          npm install -g pnpm@latest-10
          sudo wget https://raw.githubusercontent.com/jotaen/run.sh/refs/heads/main/run -O /usr/bin/run && sudo chmod +x /usr/bin/run
      - name: Install
        run: run install
      - name: Code Style
        run: run format --check
      - name: Type-Check
        run: run check-types
      - name: Unit Tests
        run: run test
      - name: Build
        run: run build --prod
      - name: Publish to Cloudflare Pages
        id: cloudflare-publish
        uses: cloudflare/wrangler-action@v4
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: b41a4d3bbf853994590a9568dda2c43e
          command: pages deploy public/ --project-name=timer-jotaen-net
