name: Deploy
on: [push, workflow_dispatch]

jobs:
  deploy:
    name: Deploy (CloudFlare Pages)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        uses: actions/setup-node@v3
        with:
          node-version: '22'
      - name: Build
        run: |
          . run.sh
          run::build
      - name: Publish to Cloudflare Pages
        id: cloudflare-publish
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: b41a4d3bbf853994590a9568dda2c43e
          projectName: geektimer-jotaen-net
          directory: public/
      - name: Print URL
        run: echo ${{ steps.cloudflare-publish.outputs.url }}
